version: "3"
services:
  app:
    build: .
    volumes:
      - ./:/go/src
    tty: true
    depends_on:
      - db
    ports:
      - 8989:8989

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

